name: Run eslint and tests

on:
  schedule:
    # run every day at 00:00
    - cron:  '0 0 * * *'
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'
jobs:
  build:
    name: Test on node ${{ matrix.node-version }} and ubuntu-latest

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 13.x]

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm ci
      run: npm ci

    - name: eslint
      run: npm run eslint

    - name: test-unit
      run: npm run test-unit

    - name: test-build
      run: npm run build && npm run install-example && npm run build-example

    - name: test-integration
      run: |
        sudo service mysql stop
        git clone https://github.com/streamr-dev/streamr-docker-dev.git
        sudo ifconfig docker0 10.200.10.1/24
        ${GITHUB_WORKSPACE}/streamr-docker-dev/streamr-docker-dev/bin.sh start --wait
        npm run test-integration
  streamr-client-testing-tool:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1
    - name: streamr-client tool test
      continue-on-error: true
      run: |
        sudo service mysql stop
        if [ ! -d streamr-docker-dev ]; then # Skip clone on subsequent attemps.
         git clone https://github.com/streamr-dev/streamr-docker-dev.git
        fi
        sudo ifconfig docker0 10.200.10.1/24
        ${GITHUB_WORKSPACE}/streamr-docker-dev/streamr-docker-dev/bin.sh start smart-contracts-init nginx engine-and-editor --wait
        echo "Testing Tool setup"
        git clone https://github.com/streamr-dev/streamr-client-testing.git
        cd ${GITHUB_WORKSPACE}/streamr-client-testing
        echo "Setup packagejson to use PR JS client"
        sed -i "s/com.streamr:client:1.3.0/com.streamr:client:+/g" build.gradle
        sed -i "s/\"streamr-client\": \"\^3.1.2\"/\"streamr-client\":\"PATH\"/g" package.json
        ## fix for escaping / of workspace path
        sed -i "s|"PATH"|"${GITHUB_WORKSPACE}"|g" package.json
        echo "Prepare for test"
        ## npm install is used because package-lock.json could be form a previous client version.
        npm install
        ./gradlew fatjar
        echo "Run streamr-client test"
        java -jar build/libs/client_testing-1.0-SNAPSHOT.jar -s stream-encrypted-shared-rotating-signed -m test
