name: Slack-Notifier
on:
  workflow_run:
    workflows: ["*"]
    types: [completed]

jobs:
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure'}}
    steps:
      - uses: actions/checkout@v2
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: network-log
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
          SLACK_ICON: https://avatars.githubusercontent.com/u/8115255?s=200&v=4
          SLACK_MESSAGE: More details on ${{ github.event.workflow_run.workflow_url.html_url }}
          SLACK_TITLE: ${{ github.event.workflow.name }} run failed
          SLACK_USERNAME: Network-Monorepo-GitAction
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MSG_AUTHOR: ${{ github.event.workflow_run.workflow_url.head_commit.author.name }}