---
name: Build with self-hosted runner
on:
  workflow_dispatch:

defaults:
  run:
    working-directory: packages/broker

jobs:
  build:
    name: Self-Hosted Build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 16.x
      - name: npm ci
        working-directory: './'
        run: |
          npm install -g npm@8
          npm run bootstrap-pkg streamr-broker
      - run: npm run eslint
      - run: npm run test-unit
